### PR TITLE
Lock entries

### PR DESCRIPTION
**Pull request by Utalange**
There are two topics: "Lock entries" and "Remove lock entries". There are so closely connected that I created them both. Only "Lock Entries" is needed for Cockpit components overview.

### CODE REVIEW

**Comment by FKlopfer** [comment]
Revie done

**Comment by Utalange** [comment]
Hendrik, please review:

- lock-entries.adoc
- remove-lock.adoc

**Comment by Utalange** [comment]
Great. There is a missing icon in lock-entries.adoc.  We usually include the icon before the title. Neptune provided us with a library of all the icons for  the Cockpit components. The icon for "lock entries" is missing. Can you perhaps check with someone?

**Comment by H3nH4453** [comment]
we use this one in the platform. Do you have it? 
image

**Comment by Utalange** [comment]
Thanks, I can use that.

**Pull request merged**
