### PR TITLE
Tiles

### PR DESCRIPTION
**Pull request by Utalange**
Please review:

tiles.adoc
tile-groups.adoc
adaptive-designer.adoc

### CODE REVIEW

**Comment by hehannken** [comment]
Review done, see comments in adaptive-designer.adoc, cockpit-components.adoc, tile-groups.adoc and tiles.adoc

**Comment by Utalange** [comment]
Pleaes review adaptive-designer.adoc, tile-groups.adoc and tiles.adoc. Ignore "cockpit-components.adoc", topic is not ready.

**Comment by H3nH4453** [comment]
Hier brauchen wir neue Screenshots. Ich werde nach Helles Vorgaben welche erstellen.

**Comment by H3nH4453** [comment]
Review done

**Pull request merged**
